### ISSUE TITLE
Use reusable workflows

### ISSUE THREAD

**Issue by rbudhrani** [QuTech-Delft/QMI#76]
Description 
=========== 
Our pipelines have several steps that are the same. We can refactor our pipelines to use [reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows). For example we can define a workflow `mypy.yml` and use that in our pipelines, instead of rewriting the same mypy step in each pipeline. This also allows us to easily incorporate existing steps/jobs in each pipeline.

Modules to be created 
--------------------- 
- n/a

Modules to be modified
---------------------- 
- n/a

Tests to be created/updated 
--------------------------- 
- n/a

Documentation to be updated 
--------------------------- 
- n/a

Hardware 
-------- 
- n/a

**Comment by heevasti** [comment]
This is done together with #96 in #97
